### ISSUE TITLE
SparseLists fail to compress with conditionals

### ISSUE THREAD

**Issue by Cece2520** [willow-ahrens/Finch.jl#135]
SparseLists will store a value every time a conditional is evaluated, even if it is the background value.

For each case, I used
`B = @fiber(sl(e(0)), [0, 1, 2, 0, 1])`
`A = @fiber(sl(e(0), 5))`

Case 1: Condition on background value, conditional evaluated at every element
`@finch @loop i A[i] = ifelse(B[i] == 0, 1, 0)`
Output for A: `Fiber(SparseList{Int64, Int64}(Element{0, Int64}([1, 0, 0, 1, 0]), 5, [1, 6], [1, 2, 3, 4, 5]))`

Case 2: Condition on non-background value, conditional evaluated at every non-background element
`@finch @loop i A[i] = ifelse(B[i] == 1, 1, 0)`
Output: `Fiber(SparseList{Int64, Int64}(Element{0, Int64}([1, 0, 1]), 5, [1, 4], [2, 3, 5]))`

Case 3: Condition on background value, set background value to background value (Behaves correctly!)
`@finch @loop i A[i] = ifelse(B[i] == 0, 0, 1)`
Output: `Fiber(SparseList{Int64, Int64}(Element{0, Int64}([1, 1, 1]), 5, [1, 4], [2, 3, 5]))`

Case 4: Use boolean expression instead of ifelse. Has same issues as ifelse. Using `convert(Int64, ...)` did not fix issue.
`@finch @loop i A[i] = (B[i] == 1)`
Output: `Fiber(SparseList{Int64, Int64}(Element{0, Int64}([1, 0, 1]), 5, [1, 4], [2, 3, 5]))`

**Comment by willow-ahrens** [comment]
The issue here is that the compiler cannot say that a stored value of B is not zero (it might be an explicit zero). Here is what the compiler can infer:

1. The expression is either `ifelse(0 == 0, 1, 0) = 1` or `ifelse(B.lvl.lvl.val[p] == 0, 1, 0) = ?`, the compiler can't tell that either case should be zero. 
2. The expression is either `ifelse(0 == 1, 1, 0) = 0` or `ifelse(B.lvl.lvl.val[p] == 1, 1, 0) = ?`, so the stored values are the cases where B was not zero.
3. The expression is either `ifelse(0 == 0, 0, 1) = 0` or `ifelse(B.lvl.lvl.val[p] == 0, 0, 1) = ?`.
4. The expression is either `(0 == 1) = false` or `(B.lvl.lvl.val[p] == 1) = ?`

**Comment by willow-ahrens** [comment]
All of these cases look correct to me, but it seems like really you'd like to ask if B has stored a value (not whether the value is zero). Is that correct? For now, the best I can offer is to use the `pattern!()` function.

**Comment by willow-ahrens** [comment]
You can currently for example do
```
julia> Bp = pattern!(B)
SparseList (false) [1:5]
├─[2]: true
├─[3]: true
├─[5]: true

julia> @finch (A .= 0; @loop i A[i] = ifelse(!Bp[i], 0, 1))
(A = Fiber(SparseList{Int64, Int64}(Element{0, Int64}([1, 1, 1]), 5, [1, 4], [2, 3, 5])),)

julia> @finch (A .= 0; @loop i A[i] = ifelse(Bp[i], 0, 1))
(A = Fiber(SparseList{Int64, Int64}(Element{0, Int64}([1, 1]), 5, [1, 3], [1, 4])),)

```

**Comment by Cece2520** [comment]
Okay, that makes sense. The example I gave was just a toy test case I used to try and figure out what was going on. In the actual code, it was a 2D array and the problem was that it ran out of memory. I think the solution will probably be to compute and reconstruct each column as a SparseList one at a time. 

In any case, since it's not a bug, I'll close the issue. This was just something I noticed while trying to change the background value.
