### ISSUE TITLE
Usage with index set construction

### ISSUE THREAD

**Issue by ericphanson** [willow-ahrens/Finch.jl#318]
Is it possible to write a Finch kernel for
```julia
function subXTv!(XTv::AbstractVector, x::AbstractMatrix, v::AbstractVector, I::Vector{Int}, sizeI::Int)
    @views begin
        xx = x[:, I[1:sizeI]]
        vv = v[1:sizeI]
    end
    return mul!(XTv, xx, vv)
end
```
where `x` is sparse, and `v` is dense?

I can write a non-Finch SparseMatrixCSC kernel with
```julia
cols = 1:sizeI
vals = nonzeros(x)
rows = rowvals(x)
XTv .= 0
for col in cols
    b_value = @inbounds v[col]
    nzr = nzrange(x, I[col])
    @fastmath @inbounds @simd for i in nzr
        row = rows[i]
        val = vals[i]
        XTv[row] += val * b_value
    end
end
```
though it needs a bunch of extra workspace to parallelize (I need to have `n_tasks` copies of `XTv`, accumulate into each separately over a subset of the columns, then add them together).

**Comment by wraith1995** [comment]
@ericphanson This is very possible. You can certainly read out indirect views of x and a portion of v as you suggest because Finch supports indirect access so you can write `x[k, I[i]]` (or if statements (e.g. if `j == I[i]`, if you prefer) and because Finch supports loops over a range `j = 1:sizeI`.  With these ingredients, you should be able to write a version of your kernel. One complication might be the format of XTv. If this is dense, it is easy. If it is sparse. then you might need to write more complex code.

We are in the process of adding parallelism, but the optimization of using workspaces to parallelize the kernel might be possible already.
