### ISSUE TITLE
Make dimensions mutable

### ISSUE THREAD

**Issue by mtsokol** [willow-ahrens/Finch.jl#393]
As discussed in https://github.com/willow-ahrens/Finch.jl/pull/390#issuecomment-1915566505 dimensions of a Tensor could be mutable to allow modifying an existing Tensor (e.g. when materializing a swizzle) instead of creating a new one.

**Comment by willow-ahrens** [comment]
One challenge with making dimensions mutable is that we'll need to be more careful about when we reconstruct levels. i.e. any time we do `foo(lvl::SparseListLevel) = SparseListLevel(foo(lvl.lvl))` we would need to change that code to preserve the original pointer to SparseListLevel. We might be able to get around that by doing `struct SparseListLevel shape::Ref{Ti}`, so that we can reconstruct the level struct but pass in a pointer to the shape independently. I'm not sure what the cost of this is. But yes, I think the compiler assumed immutability quite a bit, and we would need to be more careful about modify vs. reconstruct.

**Comment by willow-ahrens** [comment]
Another point here: mutability alone doesn't solve our problems, SparseMatrixCSC for example is a julia StdLib array with immutable dimensions.

**Comment by willow-ahrens** [comment]
Its looking like we are not going to go forward with this one actually, but instead use return statements to take immutability seriously
