### ISSUE TITLE
0 Based Internal Vectors for Fibers

### ISSUE THREAD

**Issue by Wimmerer** [willow-ahrens/Finch.jl#99]
0-based languages will have sparse arrays represented internally by 0 based vectors. While Fibers should always use `getindex` starting with 1, support for internal 0 based representation is key for workloads that are, for instance, solver-centric.

**Comment by willow-ahrens** [comment]
I agree we should implement this, there's a question of how much parameterization we should expose.

Most of the levels are parameterized with a `Tp` argument, specifying the integer type of positions in the fiber. However, the user probably doesn't want to change this property on a per-level basis (it would cause type instability). We can default Tp to be the same position type as that used by the sublevel (it currently just defaults to `Int`, so you have to set it for every level if you want to deviate).

The next challenge is of course 0 or 1 indexing. We can change the starting position to 0 with the same mechanism as above, no problem. However, for indices it's a different story. People might want to index their tensor with BigInt starting at -7, a different problem than the kind of "starting index isn't 1" that we talk about here. When we store to a binary format or reinterpret for another language, we do need to shift the stored values of the indices. Perhaps the answer to this problem is more granular, and should involve interpreting 0-indexed arrays as 0-indexed _in julia_, then shifting them by one _in julia_ as well. I'm open to other suggestions.

**Comment by willow-ahrens** [comment]
so the operation to read a 0-indexed vector from memory would look like
```
A_raw = fbrread("A.fbr")
A_raw::Fiber{SparseListLevel{Int, 0, ElementLevel{0.0, Float64, 0}}}
A = Fiber!(SparseListLevel{Int, 1, ElementLevel{0.0, Float64, 1}}}
@finch @loop j i A[i] = A_raw[i-1]
```

**Comment by willow-ahrens** [comment]
Alternately, we can say that fibers always start at `one(Ti)` or `zero(Ti)`, and this is determined by whether the positions start at one or zero as well.

**Comment by Wimmerer** [comment]
I currently have a `Bi` parameter which isn't really constrained but is assumed to be 1 or 0. So that seems to match up well?

**Comment by willow-ahrens** [comment]
Two things need to work:1. Fibers indexed from 1, 0, or -72. Fibers indexed from 1 that subtract one internally (storage looks 0 indexed, semantics look 1 indexed)I am trying to figure out if I can do both at once or if these need to be separate concepts.On Mar 9, 2023, at 12:01 PM, Will Kimmerer ***@***.***> wrote:﻿
I currently have a Bi parameter which isn't really constrained but is assumed to be 1 or 0. So that seems to match up well?

**Comment by Wimmerer** [comment]
Why -72? Note this is strictly for internal Vectors, I only intend to support 1 based indexing right now for `getindex` and `setindex`

**Comment by willow-ahrens** [comment]
What I'm saying is that I'd like Finch to support overloaded implementations of base.axes, and I'm starting to understand this as a separate concern from whether Finch stores zero or one indexed.

As a related concern, Finch may one day support a C backend, and so would need to write code which is zero-indexed for zero-indexed arrays.

**Comment by willow-ahrens** [comment]
I think that the way forward on this issue is to do one of the following 3 options:
1. Define an integer wrapper number type that stores the value it represents off by one, and promotes with other integers as +1.
2. Define a vector type that stores integers off by one
3. Add some parameter to Fibers to do the +1 and -1 in the code that Finch generates.

**Comment by willow-ahrens** [comment]
consider the following:
```

struct CIndex{T} <: Integer
    val::T
end

cindex_types = [Bool, Int8, Int16, Int32, Int64, Int128, UInt8, UInt16, UInt32, UInt64, UInt128, BigInt]
for S in cindex_types
    @eval begin
        @inline Base.promote_rule(::Type{CIndex{T}}, ::Type{$S}) where {T} = CIndex{promote_type(T, $S)}
        Base.convert(::Type{CIndex{T}}, i::$S) where {T} = CIndex(convert(T, i - true))
    end
end
Base.promote_rule(::Type{CIndex{T}}, ::Type{CIndex{S}}) where {T, S} = CIndex{promote_type(T, S)}

cindex_binops = [:*, :+]

for Ti in cindex_types, op in cindex_binops
    @eval @inline Base.$op(a::CIndex{T}, b::CIndex{T}) where {T} = CIndex($op(a.val + true, b.val + true)-true)
end

Base.to_index(i::CIndex) = Base.to_index(i.val + true)
```

**Comment by willow-ahrens** [comment]
http://willowahrens.io/Finch.jl/dev/fibers/#Index-Compatibility
